## Timing File for GPS Synchronized Clock

# Create 50MHz Clock
create_clock -name clk -period 20.000 [get_ports {	clk	}]

# Input Timing
set_false_path	-from	[get_ports	{	reset	}]
set_false_path	-from	[get_ports	{	pps	}]
set_false_path	-from	[get_ports	{	uart_data	}]
set_false_path	-from	[get_ports	{	brightness_button	}]
set_false_path	-from	[get_ports	{	time_button	}]
set_false_path	-from	[get_ports	{	misc_button	}]

# Output Timing
set_false_path -to [get_ports {	uart_rx	}]
set_false_path -to [get_ports {	gps_lock	}]

set_false_path -to [get_ports {	misc_leds[0]	}]
set_false_path -to [get_ports {	misc_leds[1]	}]
set_false_path -to [get_ports {	misc_leds[2]	}]
set_false_path -to [get_ports {	misc_leds[3]	}]
set_false_path -to [get_ports {	misc_leds[4]	}]

set_false_path -to [get_ports {	led1[0]	}]
set_false_path -to [get_ports {	led1[1]	}]
set_false_path -to [get_ports {	led1[2]	}]
set_false_path -to [get_ports {	led1[3]	}]
set_false_path -to [get_ports {	led1[4]	}]
set_false_path -to [get_ports {	led1[5]	}]
set_false_path -to [get_ports {	led1[6]	}]

set_false_path -to [get_ports {	led2[0]	}]
set_false_path -to [get_ports {	led2[1]	}]
set_false_path -to [get_ports {	led2[2]	}]
set_false_path -to [get_ports {	led2[3]	}]
set_false_path -to [get_ports {	led2[4]	}]
set_false_path -to [get_ports {	led2[5]	}]
set_false_path -to [get_ports {	led2[6]	}]

set_false_path -to [get_ports {	led3[0]	}]
set_false_path -to [get_ports {	led3[1]	}]
set_false_path -to [get_ports {	led3[2]	}]
set_false_path -to [get_ports {	led3[3]	}]
set_false_path -to [get_ports {	led3[4]	}]
set_false_path -to [get_ports {	led3[5]	}]
set_false_path -to [get_ports {	led3[6]	}]

set_false_path -to [get_ports {	led4[0]	}]
set_false_path -to [get_ports {	led4[1]	}]
set_false_path -to [get_ports {	led4[2]	}]
set_false_path -to [get_ports {	led4[3]	}]
set_false_path -to [get_ports {	led4[4]	}]
set_false_path -to [get_ports {	led4[5]	}]
set_false_path -to [get_ports {	led4[6]	}]

set_false_path -to [get_ports {	led5[0]	}]
set_false_path -to [get_ports {	led5[1]	}]
set_false_path -to [get_ports {	led5[2]	}]
set_false_path -to [get_ports {	led5[3]	}]
set_false_path -to [get_ports {	led5[4]	}]
set_false_path -to [get_ports {	led5[5]	}]
set_false_path -to [get_ports {	led5[6]	}]

set_false_path -to [get_ports {	led6[0]	}]
set_false_path -to [get_ports {	led6[1]	}]
set_false_path -to [get_ports {	led6[2]	}]
set_false_path -to [get_ports {	led6[3]	}]
set_false_path -to [get_ports {	led6[4]	}]
set_false_path -to [get_ports {	led6[5]	}]
set_false_path -to [get_ports {	led6[6]	}]

set_false_path -to [get_ports {	led7[0]	}]
set_false_path -to [get_ports {	led7[1]	}]
set_false_path -to [get_ports {	led7[2]	}]
set_false_path -to [get_ports {	led7[3]	}]
set_false_path -to [get_ports {	led7[4]	}]
set_false_path -to [get_ports {	led7[5]	}]
set_false_path -to [get_ports {	led7[6]	}]

set_false_path -to [get_ports {	led8[0]	}]
set_false_path -to [get_ports {	led8[1]	}]
set_false_path -to [get_ports {	led8[2]	}]
set_false_path -to [get_ports {	led8[3]	}]
set_false_path -to [get_ports {	led8[4]	}]
set_false_path -to [get_ports {	led8[5]	}]
set_false_path -to [get_ports {	led8[6]	}]

set_false_path -to [get_ports {	led9[0]	}]
set_false_path -to [get_ports {	led9[1]	}]
set_false_path -to [get_ports {	led9[2]	}]
set_false_path -to [get_ports {	led9[3]	}]
set_false_path -to [get_ports {	led9[4]	}]
set_false_path -to [get_ports {	led9[5]	}]
set_false_path -to [get_ports {	led9[6]	}]